const KEY = 'delivery-desk-v4';
const SHARED_STATE_URL = '/api/state';
const driverTheme = document.createElement('style');
driverTheme.textContent = `
  .column.driver-a .chead { background:#eaf2ff; border-bottom:3px solid #3377e8; } .column.driver-a .cap { color:#2056b7; } .column.driver-a .card { border-left-color:#3377e8; }
  .column.driver-b .chead { background:#fff0ed; border-bottom:3px solid #f05d5e; } .column.driver-b .cap { color:#b94343; } .column.driver-b .card { border-left-color:#f05d5e; }
  .column.driver-c .chead { background:#f2edff; border-bottom:3px solid #7a58c8; } .column.driver-c .cap { color:#6940b6; } .column.driver-c .card { border-left-color:#7a58c8; }
  .column.driver-d .chead { background:#e9f8ef; border-bottom:3px solid #28814b; } .column.driver-d .cap { color:#216d40; } .column.driver-d .card { border-left-color:#28814b; }
  @media (max-width:540px) { .column .chead { border-bottom-width:4px; } .column .chead h2 { font-weight:900; } }
`;
document.head.append(driverTheme);

const defaults = { origin: { name: 'ベイシアなめがわモール店', address: '埼玉県比企郡滑川町羽尾2780' }, drivers: [{ id: 'a', name: 'ドライバー A', limit: 350 }, { id: 'b', name: 'ドライバー B', limit: 350 }], master: [{ id: 'water', label: '飲料ケース', terms: ['水', '飲料', 'ドリンク', 'お茶', 'ケース'], pt: 2, weight: 13 }, { id: 'cl', label: 'クーラー大', terms: ['クーラー大', '保冷大'], pt: 1.5, weight: 9 }, { id: 'cs', label: 'クーラー小', terms: ['クーラー小', '保冷小'], pt: .8, weight: 4.5 }, { id: 'xl', label: 'コンテナ大', terms: ['コンテナ大', '箱大'], pt: 1, weight: 6.5 }, { id: 'xs', label: 'コンテナ小', terms: ['コンテナ小', '箱小', 'コンテナ'], pt: .5, weight: 3 }], days: {} };
const $ = (id) => document.getElementById(id);
const clone = (value) => JSON.parse(JSON.stringify(value));
let state;
try { state = { ...clone(defaults), ...JSON.parse(localStorage.getItem(KEY)) }; } catch { state = clone(defaults); }
let workDate = new Date().toISOString().slice(0, 10);
let slot = '10時便';
let draggedId = null;
let remoteRevision = Number(state.revision) || 0;
const sharedMode = location.protocol === 'http:' || location.protocol === 'https:';
function isSharedState(value) { return value && typeof value === 'object' && value.origin && Array.isArray(value.drivers) && Array.isArray(value.master) && value.days && typeof value.days === 'object'; }
function save() { localStorage.setItem(KEY, JSON.stringify(state)); if (sharedMode) void saveSharedState(); }
async function saveSharedState() { try { const response = await fetch(SHARED_STATE_URL, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(state) }); if (!response.ok) throw new Error(); const saved = await response.json(); remoteRevision = Number(saved.revision) || remoteRevision; state.revision = remoteRevision; localStorage.setItem(KEY, JSON.stringify(state)); } catch { $('message').textContent = '共有サーバーへ接続できません。端末内には保存されています。'; } }
async function loadSharedState() { if (!sharedMode) return; try { const response = await fetch(SHARED_STATE_URL, { cache: 'no-store' }); if (!response.ok) throw new Error(); const shared = await response.json(); const revision = Number(shared.revision) || 0; if (isSharedState(shared) && revision > remoteRevision) { state = shared; remoteRevision = revision; localStorage.setItem(KEY, JSON.stringify(state)); render(); } else if (revision === 0) { await saveSharedState(); } } catch { /* Local state remains usable when the service is unavailable. */ } }
function deliveries() { state.days[workDate] ??= {}; state.days[workDate][slot] ??= []; return state.days[workDate][slot]; }
function totals(items) { return items.reduce((result, item) => ({ pt: result.pt + item.totalPt, weight: result.weight + item.weight }), { pt: 0, weight: 0 }); }
function quantity(value) { const match = String(value).match(/([0-9０-９]+|[一二三四五六七八九十]+)(?:個|つ|本|ケース)?$/); if (!match) return 1; const kanji = { 一: 1, 二: 2, 三: 3, 四: 4, 五: 5, 六: 6, 七: 7, 八: 8, 九: 9, 十: 10 }; const normalized = match[1].replace(/[０-９]/g, (digit) => String.fromCharCode(digit.charCodeAt(0) - 0xfee0)); return Number(normalized) || kanji[normalized] || 1; }
function parseCargoes(text) { const cargoText = text.replace(/[0-9０-９]+(?:[.．][0-9０-９]+)?\s*(?:km|ＫＭ|キロ|كيلومتر)/gi, ''); const compact = cargoText.replace(/[\s、,，。]/g, ''); const found = []; const add = (item, term) => found.push({ masterId: item.id, label: item.label, qty: quantity(term), pt: Number(item.pt), weight: Number(item.weight) }); state.master.forEach((item) => item.terms.forEach((term) => (compact.match(new RegExp(`${term}(?:[0-9０-９]+|[一二三四五六七八九十]+)?`, 'g')) || []).forEach((match) => add(item, match)))); if (/コンテナ大小|コンテナ小大/.test(compact)) ['コンテナ大', 'コンテナ小'].forEach((label) => { const item = state.master.find((entry) => entry.label === label); if (item && !found.some((entry) => entry.masterId === item.id)) add(item, label); }); return found; }
function distanceFrom(raw, fallback = null) { const match = raw.match(/([0-9０-９]+(?:[.．][0-9０-９]+)?)\s*(?:km|ＫＭ|キロ|كيلومتر)/i); if (!match) return fallback; return Number(match[1].replace(/[０-９．]/g, (character) => character === '．' ? '.' : String.fromCharCode(character.charCodeAt(0) - 0xfee0))); }
function parseDelivery(raw, previous = {}) { const name = raw.split(/[、,，。]/)[0].trim(); if (!name) return null; const cargoes = parseCargoes(raw); const cargoPt = cargoes.reduce((sum, item) => sum + item.pt * item.qty, 0); const weight = cargoes.reduce((sum, item) => sum + item.weight * item.qty, 0); const distanceKm = distanceFrom(raw, previous.distanceKm ?? null); const distancePt = distanceKm ?? 1.5; return { id: previous.id || crypto.randomUUID(), raw, name, address: name.startsWith('埼玉県') ? name : `埼玉県${name}`, cargoes, cargoPt, weight, distanceKm, distancePt, totalPt: distancePt + cargoPt, driverId: previous.driverId || null, status: previous.status || '未配達' }; }
function mapsUrl(address) { return `https://www.google.com/maps/dir/?${new URLSearchParams({ api: '1', origin: `${state.origin.name} ${state.origin.address}`, destination: address, travelmode: 'driving' })}`; }
function autoAssign() { const items = deliveries(); items.forEach((item) => { item.driverId = null; }); [...items].sort((a, b) => b.weight - a.weight).forEach((item) => { const driver = state.drivers.map((entry) => ({ ...entry, ...totals(items.filter((delivery) => delivery.driverId === entry.id)) })).sort((a, b) => a.weight - b.weight || a.pt - b.pt)[0]; item.driverId = driver.id; }); }
function move(item, direction) { const items = deliveries(); const from = items.indexOf(item), to = from + direction; if (to < 0 || to >= items.length) return; [items[from], items[to]] = [items[to], items[from]]; save(); render(); }
function card(item) { const element = document.createElement('article'); element.className = 'card'; element.draggable = true; element.innerHTML = '<div class="top"><strong></strong><button class="mini danger delete">削除</button></div><div class="cargo"></div><div class="meta"></div><div class="actions"><a class="mini map" target="_blank" rel="noopener noreferrer">地図</a><input class="distance-input" type="number" min="0" step="0.1" aria-label="走行距離 km" placeholder="距離 km"><button class="mini edit">編集・再解析</button><button class="mini up">上へ</button><button class="mini down">下へ</button><select class="smallselect"><option>未配達</option><option>配達完了</option><option>不在</option><option>持ち戻り</option></select></div>';
  element.querySelector('strong').textContent = item.name;
  element.querySelector('.cargo').textContent = item.cargoes.length ? `荷物: ${item.cargoes.map((cargo) => `${cargo.label} ${cargo.qty}個`).join(' / ')}` : '荷物: 未入力';
  element.querySelector('.meta').textContent = `距離 ${item.distanceKm === null || item.distanceKm === undefined ? '概算' : `${item.distanceKm.toFixed(1)} km`} ${item.distancePt.toFixed(1)} pt + 荷物 ${item.cargoPt.toFixed(1)} pt / ${item.weight.toFixed(1)} kg`;
  element.querySelector('.map').href = mapsUrl(item.address);
  const distanceInput = element.querySelector('.distance-input'); distanceInput.value = item.distanceKm ?? ''; distanceInput.onchange = () => { const value = Number(distanceInput.value); item.distanceKm = Number.isFinite(value) && value >= 0 ? value : null; item.distancePt = item.distanceKm ?? 1.5; item.totalPt = item.distancePt + item.cargoPt; save(); render(); };
  const select = element.querySelector('select'); select.value = item.status; select.onchange = () => { item.status = select.value; save(); render(); };
  element.querySelector('.delete').onclick = () => { const items = deliveries(); items.splice(items.indexOf(item), 1); save(); render(); };
  element.querySelector('.edit').onclick = () => { const raw = prompt('住所と荷物を修正してください。', item.raw); const updated = raw !== null && parseDelivery(raw, item); if (updated) { Object.assign(item, updated); save(); render(); } };
  element.querySelector('.up').onclick = () => move(item, -1); element.querySelector('.down').onclick = () => move(item, 1); element.ondragstart = () => { draggedId = item.id; }; return element;
}
function render() { const items = deliveries(), total = totals(items); $('date').value = workDate; $('slot').value = slot; $('origin').textContent = `店舗拠点: ${state.origin.name}`; $('originAddress').textContent = state.origin.address; $('count').textContent = items.length; $('points').textContent = `${total.pt.toFixed(1)} pt`; $('weight').textContent = `${total.weight.toFixed(1)} kg`; $('attention').textContent = items.filter((item) => !item.driverId || ['不在', '持ち戻り'].includes(item.status)).length; const dispatch = $('dispatch'); dispatch.style.setProperty('--drivers', state.drivers.length); dispatch.replaceChildren(); [{ id: null, name: '未配車' }, ...state.drivers].forEach((driver, index) => { const assigned = items.filter((item) => item.driverId === driver.id), total = totals(assigned), over = driver.limit && total.weight > driver.limit; const column = document.createElement('section'); column.className = `column ${driver.id ? `driver-${String.fromCharCode(97 + index - 1)}` : ''}`; column.innerHTML = '<div class="chead"><h2></h2><span class="cap"></span></div><div class="zone"></div>'; column.querySelector('h2').textContent = driver.name; const cap = column.querySelector('.cap'); cap.textContent = driver.id ? `${total.weight.toFixed(1)} / ${driver.limit} kg${over ? ' 上限超過' : ''}` : `${assigned.length} 件`; if (over) cap.classList.add('over'); const zone = column.querySelector('.zone'); zone.ondragover = (event) => { event.preventDefault(); zone.classList.add('hover'); }; zone.ondragleave = () => zone.classList.remove('hover'); zone.ondrop = (event) => { event.preventDefault(); const item = items.find((entry) => entry.id === draggedId); if (item) { item.driverId = driver.id; save(); render(); } }; assigned.length ? assigned.forEach((item) => zone.append(card(item))) : zone.innerHTML = `<p class="empty">${driver.id ? 'ここへドラッグ' : '追加した配送先が表示されます'}</p>`; dispatch.append(column); }); renderHistory(); }
function renderHistory() { const list = $('history'); list.replaceChildren(); Object.keys(state.days).sort().reverse().forEach((date) => { const count = Object.values(state.days[date]).reduce((sum, items) => sum + items.length, 0); const button = document.createElement('button'); button.textContent = `${date} (${count} 件)`; button.onclick = () => { workDate = date; render(); }; const item = document.createElement('li'); item.append(button); list.append(item); }); }
function renderSettings() { const drivers = $('drivers'), master = $('master'); drivers.replaceChildren(); master.replaceChildren(); state.drivers.forEach((driver) => { const row = document.createElement('div'); row.className = 'row driverrow'; row.innerHTML = `<input value="${driver.name}"><input type="number" value="${driver.limit}"><button class="mini danger">削除</button>`; row.querySelector('button').onclick = () => { if (state.drivers.length > 1) { state.drivers = state.drivers.filter((entry) => entry !== driver); renderSettings(); } }; drivers.append(row); }); state.master.forEach((item) => { const row = document.createElement('div'); row.className = 'row'; row.innerHTML = `<input value="${item.label}" title="品目名"><input value="${item.terms.join(',')}" title="認識語（カンマ区切り）"><input type="number" step=".1" value="${item.pt}" title="ポイント"><input type="number" step=".1" value="${item.weight}" title="重量"><button class="mini danger">削除</button>`; row.querySelector('button').onclick = () => { state.master = state.master.filter((entry) => entry !== item); renderSettings(); }; master.append(row); }); }
function saveSettings() { state.origin.name = $('shopName').value.trim() || defaults.origin.name; state.origin.address = $('shopAddress').value.trim() || defaults.origin.address; state.drivers = [...$('drivers').children].map((row, index) => ({ id: state.drivers[index]?.id || crypto.randomUUID(), name: row.children[0].value.trim() || `ドライバー ${index + 1}`, limit: Number(row.children[1].value) || 350 })); state.master = [...$('master').children].map((row, index) => ({ ...state.master[index], id: state.master[index]?.id || crypto.randomUUID(), label: row.children[0].value.trim() || '荷物', terms: row.children[1].value.split(',').map((term) => term.trim()).filter(Boolean), pt: Number(row.children[2].value) || 0, weight: Number(row.children[3].value) || 0 })); save(); $('settings').hidden = true; render(); }
function add() { const item = parseDelivery($('input').value.trim()); if (!item) { $('message').textContent = '住所を入力してください。'; return; } deliveries().push(item); $('input').value = ''; autoAssign(); save(); render(); $('message').textContent = '自動配分しました。カードをドラッグして手動調整し、地図で経路を確認してください。'; }
function copyPrevious() { const source = Object.keys(state.days).filter((date) => date < workDate).sort().reverse().map((date) => state.days[date][slot]).find((items) => items?.length); if (!source) { $('message').textContent = '複製できる過去の同一便がありません。'; return; } deliveries().push(...clone(source).map((item) => ({ ...item, id: crypto.randomUUID(), driverId: null, status: '未配達' }))); save(); render(); }
function csv() { const rows = [['日付', '便', '担当', '配送先', '荷物', 'ポイント', '重量kg', '状態'], ...deliveries().map((item) => [workDate, slot, state.drivers.find((driver) => driver.id === item.driverId)?.name || '未配車', item.name, item.cargoes.map((cargo) => `${cargo.label}${cargo.qty}個`).join(' / '), item.totalPt.toFixed(1), item.weight.toFixed(1), item.status])]; const blob = new Blob(['\uFEFF' + rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `配送_${workDate}_${slot}.csv`; link.click(); URL.revokeObjectURL(link.href); }
$('add').onclick = add; $('input').onkeydown = (event) => { if (event.key === 'Enter') add(); }; $('date').onchange = (event) => { workDate = event.target.value; render(); }; $('slot').onchange = (event) => { slot = event.target.value; render(); }; $('copy').onclick = copyPrevious; $('csv').onclick = csv; $('print').onclick = () => print(); $('openSettings').onclick = () => { $('settings').hidden = false; $('shopName').value = state.origin.name; $('shopAddress').value = state.origin.address; renderSettings(); }; $('closeSettings').onclick = () => { $('settings').hidden = true; }; $('saveSettings').onclick = saveSettings; $('addDriver').onclick = () => { state.drivers.push({ id: crypto.randomUUID(), name: '新しいドライバー', limit: 350 }); renderSettings(); }; $('addMaster').onclick = () => { state.master.push({ id: crypto.randomUUID(), label: '新しい荷物', terms: [], pt: 0, weight: 0 }); renderSettings(); }; const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition || !window.isSecureContext) $('mic').disabled = true; else $('mic').onclick = () => { const recognition = new Recognition(); recognition.lang = 'ja-JP'; recognition.onresult = (event) => { $('input').value = event.results[0][0].transcript; add(); }; recognition.start(); }; render(); void loadSharedState(); if (sharedMode) setInterval(loadSharedState, 3000);